import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import CenterBox from "./components/CenterBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`bg-gradient-to-br from-lightpurple to-darkpurple p-4 text-white${inter.className}`} >
      <div>
       <Header> </Header>
        <CenterBox>

        {children}

       </CenterBox>
       
      </div>
      </body>
      
      
    </html>
  );
}
